// Generated by CoffeeScript 1.7.1
(function() {
  window.addEventListener("DOMContentLoaded", (function() {
    var errBack, videoObj;
    window.canvas = document.getElementById("canvas");
    window.context = canvas.getContext("2d");
    window.video = document.getElementById("video");
    videoObj = {
      video: true
    };
    errBack = function(error) {
      return console.log("Video capture error:", error.code);
    };
    if (navigator.getUserMedia) {
      return navigator.getUserMedia(videoObj, (function(stream) {
        video.src = stream;
        return video.play();
      }), errBack);
    } else if (navigator.webkitGetUserMedia) {
      return navigator.webkitGetUserMedia(videoObj, (function(stream) {
        video.src = window.webkitURL.createObjectURL(stream);
        return video.play();
      }), errBack);
    } else if (navigator.mozGetUserMedia) {
      return navigator.mozGetUserMedia(videoObj, (function(stream) {
        video.src = window.URL.createObjectURL(stream);
        return video.play();
      }), errBack);
    }
  }), false);

  document.getElementById("snap").addEventListener("click", function() {
    console.log("Snapping");
    return setInterval((function() {
      context.drawImage(video, 0, 0, 640, 480);
      context.rect(0, 0, 100, 100);
      context.fillStyle = 'yellow';
      return context.fill();
    }), 40);
  });

}).call(this);
